---
# Steps to test Lacp config after running the playbook
#
#      - View bonding configuration: cat /proc/net/bonding/bond0
#      - View Active slave: cat /sys/class/net/bond0/bonding/active_slave
#      - ping -I bond0 [bond0_ip]
#      - ifdown [primary_slave_interface]. Verify active slave switches to secondary slave interface.
#      - ifup [primary_slave_interface]. Verify active slave switched back to primary slave
#      - Ping traffic should not get interrupted during active-passive failover.
#
#

- hosts: testvm
  gather_facts: false
  become: true
  tasks:
   - name: install package
     apt:
      name: ifenslave
      state: present
   - name: copy required kernel modules at boot
     copy:
      src: modules
      dest: /etc/modules
   - name: copy lacp network config
     copy:
      src: active-passive.cfg
      dest: /etc/network/interfaces.d/70-cloud-init.cfg
   - name: reboot server for config to take effect
     reboot:
