---

- hosts: testvm
  become: true
  gather_facts: false
  tasks:
   - name: copy executable script
     copy:
      src: ./hello
      dest: /opt
      owner: vagrant
      group: vagrant
      mode: 0755

   - name: add executable to PATH env
     lineinfile:
      path: /home/vagrant/.bashrc
      line: 'export PATH=$PATH:/opt'
      insertafter: EOF
      state: present
      create: yes

   - name: source bash profile
     shell: . /home/vagrant/.bashrc
