---

- hosts: node1
  become: true
  vars: 
   hping_attack: false
  tasks:
   - name: playbook execution begins
     debug: msg="Test suricata play started.."
   - name: perform syn flood attack
     command: "hping3 -c 4 -S 192.168.0.34 -p 80 --flood"
     when: hping_attack

   - name: perform nmap scan
     command: nmap -sS -v -n -A 192.168.0.34 -T4
